<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputApellidoPApoderado</name>
   <tag></tag>
   <elementGuidId>ad0c7af6-7223-4098-8131-cc5703cbac4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_app</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apo_app']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#apo_app</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4030cec6-7f2c-488d-81ae-bb01395a2070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85a1b4ac-3d7d-4e8c-a48a-eb3c16236b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6cb0f302-ff7c-4796-8f33-7731e58c7ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_app</value>
      <webElementGuid>ab542c21-61ac-4452-b35a-b117f3b97907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_app</value>
      <webElementGuid>c6891ce3-fd97-4a7c-87e3-37af652b6a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_app&quot;)</value>
      <webElementGuid>3ddb7da5-81d3-494d-913b-f4882e5c3486</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apo_app']</value>
      <webElementGuid>44257381-89bf-43a1-ba74-9ccde5020a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>85649f5d-8499-4234-868d-28a50e41ab38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>08446df3-6c09-4f53-84ae-41b1616052a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'apo_app' and @name = 'apo_app']</value>
      <webElementGuid>3491ac50-4b0b-40c3-8d7f-7efdcf4bc11e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
