<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_radioButtonRut</name>
   <tag></tag>
   <elementGuidId>44f5be95-a5a6-41d7-8fe6-8b5b1d9d1c81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checknacionalidad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checknacionalidad']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#checknacionalidad</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9469441b-64c2-4c0d-9c25-cca294e1bf93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>811230e1-9845-48e9-b249-6877295e9b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checknacionalidad</value>
      <webElementGuid>50b5c86c-a18a-4c57-9abc-03aa8a8f79c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checknacionalidad</value>
      <webElementGuid>04c6daf4-2521-4f65-a57a-5ae6b920dee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fd59b793-483a-40e7-8e13-a80a33dd52a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>6528b5b9-6b29-4136-ab05-4036a97415ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checknacionalidad&quot;)</value>
      <webElementGuid>348a4a4b-2a6c-4f25-9cc3-44d5c79260f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checknacionalidad']</value>
      <webElementGuid>08a1e7ee-acb5-437e-a5c4-d40e8264020a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form']/tbody/tr[4]/td/fieldset/div/table/tbody/tr/td[2]/span[2]/input</value>
      <webElementGuid>344750ae-45db-49b7-a1e2-28fb62d952dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>1aa6d5a8-67f0-41a0-a2ad-bc62de5ea5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'checknacionalidad' and @id = 'checknacionalidad']</value>
      <webElementGuid>90e41423-2bb1-4752-a7d7-ea697b9ecffa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
