<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_checkGrupDiferido</name>
   <tag></tag>
   <elementGuidId>3d782d5e-6812-4086-942e-0f1760cfdf7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#diferencial</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='diferencial']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#diferencial</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdf738a8-0340-4e4f-9048-7d452766a32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>94747340-2a6c-41d4-a0dd-7efe78d5a968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>diferencial</value>
      <webElementGuid>d4913097-b0e8-48c5-9805-912fb193407c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>diferencial</value>
      <webElementGuid>b9adcbe2-aa05-4861-805c-f026d8c5704f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>seleccion(1);</value>
      <webElementGuid>c3adc811-f5db-4ad1-b4ff-30b330ba887a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>bb278315-8843-441a-8b50-28866a4935d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;diferencial&quot;)</value>
      <webElementGuid>7a903429-7083-44db-b212-ae2bdf76b148</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='diferencial']</value>
      <webElementGuid>b304a2f8-227e-48e7-8cdc-b99d1dd902b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form_2']/tbody/tr[8]/td[2]/input</value>
      <webElementGuid>8e7b20f4-1ce6-4921-9295-dcb8e3fc6698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/input</value>
      <webElementGuid>ec4a9adc-538e-426a-9934-2a1f615403f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'diferencial' and @id = 'diferencial']</value>
      <webElementGuid>8c96845e-ce33-492d-b0a7-8a2232b0ac65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
