<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputSisSalud</name>
   <tag></tag>
   <elementGuidId>275153f0-22af-4ee7-b210-62396a012886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sist_salud</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sist_salud']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sist_salud</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>384416f6-b447-4ac1-b6f8-43d0c163e143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32d7b24a-9317-429c-86af-6f4ac0a0560a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sist_salud</value>
      <webElementGuid>f2e520d8-1c04-4f7a-b42d-9b90a09bffc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sist_salud</value>
      <webElementGuid>e73282c5-2bfd-4817-be53-db5751c43f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desplegable</value>
      <webElementGuid>1eb84c51-e337-4401-9cb4-b9c8d4d63b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>d7753aa6-6363-471a-854c-f549f611f368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validadorCaracteresComillas(this.value, this.id)</value>
      <webElementGuid>d2520f45-2cc2-42a5-a6ec-d24f7962c00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sist_salud&quot;)</value>
      <webElementGuid>bf54a617-0040-48df-a03c-611ce0540ef0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sist_salud']</value>
      <webElementGuid>bdb33c4a-7c78-4935-a6a0-48868e5264e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form']/tbody/tr[4]/td/fieldset/div/table[2]/tbody/tr[15]/td[2]/input</value>
      <webElementGuid>99087f92-535b-435f-92a4-1987e1190743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td[2]/input</value>
      <webElementGuid>57906e13-a891-4273-acd2-fcd9222e1b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'sist_salud' and @id = 'sist_salud']</value>
      <webElementGuid>0563eaa2-4185-473f-aa69-dd053c2623c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
