<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_checkTextoMineduc</name>
   <tag></tag>
   <elementGuidId>f0438ac0-4db2-4091-a336-08e3716ce52e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textosMineduc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textosMineduc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#textosMineduc</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1eb4590-d60a-454a-9b9c-57eba8c18555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>6c8f1d50-f95e-4872-aa51-62215a1f1c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4234eab2-0e03-458b-bb4a-0ca5d6c37a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textosMineduc</value>
      <webElementGuid>185ec0c1-992a-4d9b-b96d-f784cc0350e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textosMineduc</value>
      <webElementGuid>a3d64ee2-4751-401c-ae35-fb604c52344e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textosMineduc&quot;)</value>
      <webElementGuid>c7d74b34-5770-430d-b6f2-8b4aea44f1a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textosMineduc']</value>
      <webElementGuid>2e88aa18-30bf-4ea6-8a97-7c10f826337b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form_4']/tbody/tr[3]/td[6]/input</value>
      <webElementGuid>1fe8dd09-a582-4ec7-bae1-6a9536e046fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]/input</value>
      <webElementGuid>e506953d-eb67-41e5-bd6f-1f2002406d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'textosMineduc' and @id = 'textosMineduc']</value>
      <webElementGuid>56e4a7ee-6519-466b-8317-870a28dce892</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
