<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_checkUtilesEscolares</name>
   <tag></tag>
   <elementGuidId>08afa955-1139-4174-8a57-69e3e69e0d6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OtrBen3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OtrBen3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Utiles escolares&quot;s] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e47fcfb5-35bf-48d7-810a-12106ae05121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a0db4aa8-f0b0-4745-b62c-2ae7b9372a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OtrBen3</value>
      <webElementGuid>714377f1-66d5-498d-8658-f5d343e41f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OtrBen3&quot;)</value>
      <webElementGuid>709e7169-47b4-4554-a36f-ec0154c9dcdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OtrBen3']</value>
      <webElementGuid>09e6e323-3b44-4c04-a032-f88a2a5f5186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='otros_beneficios']/table/tbody/tr/td[3]/input</value>
      <webElementGuid>ae0ad9d4-c1b1-4ee3-a008-69d89d6ea1a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/table/tbody/tr/td[3]/input</value>
      <webElementGuid>718e93c8-f1da-49cf-9ae2-126696d8fbfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'OtrBen3']</value>
      <webElementGuid>30dc789c-c152-46a2-b44a-86d413172c1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
