<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_checkRepitente</name>
   <tag></tag>
   <elementGuidId>7a2d1a78-ee30-480e-9484-4d7e1c9a788a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#repitente</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='repitente']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#repitente</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fc89001-25e2-4d8a-98c2-16b9410d8fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>39</value>
      <webElementGuid>a0e8e243-2bc3-40e3-9fde-7d1cc927992d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0ec5a878-8bfd-4223-8aec-6a556034e4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repitente</value>
      <webElementGuid>f218f1d8-ee4a-447d-a526-ac11f403601d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>repitente</value>
      <webElementGuid>f30759b7-dcfb-49d5-b72e-0bf77f3fb7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>funcrepitente()</value>
      <webElementGuid>1d08a820-6ab0-468c-a7dd-13d0cad88985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repitente&quot;)</value>
      <webElementGuid>f82ad132-a966-467d-8963-119dba05dbf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='repitente']</value>
      <webElementGuid>455f0cd9-e6f7-4794-9d1b-ed21b28fbfad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form_4']/tbody/tr[3]/td[3]/input</value>
      <webElementGuid>cc00fd4d-0b78-458c-b86e-5c092a752514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/input</value>
      <webElementGuid>0489dbce-61ed-4fdb-912f-ca23241394d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'repitente' and @id = 'repitente']</value>
      <webElementGuid>659e7331-1546-4a34-84ec-5d026189ef40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
