<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inoutRut</name>
   <tag></tag>
   <elementGuidId>dab33a28-d4a1-419c-9d02-222a45b835aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rut</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rut']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ej: 12123123-2&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae0abe8b-d74f-4e06-a4f4-327f1f56b575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f7bc20ca-5e20-4202-9ab8-5ad56282d617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rut</value>
      <webElementGuid>346a3e48-19e7-409a-91b1-aea6d486cb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rut</value>
      <webElementGuid>cc25a9b5-5d27-4596-b78b-d6e555b4607f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>RUT sin puntos y con guión</value>
      <webElementGuid>e370f961-cfe2-4018-a326-2391765a30c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desplegable</value>
      <webElementGuid>f6e19523-6655-4c35-bed0-2643e6db64da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>limpiarRut(this.value, 1)</value>
      <webElementGuid>cf3dc769-b1dd-4596-ae91-d090a89fb885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>validarRut(this.value, 1);</value>
      <webElementGuid>8fec7f0c-d251-466f-8545-a7f2585ea5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ej: 12123123-2</value>
      <webElementGuid>9c0fd559-ba9e-4cdb-b249-02d28fdddf8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3990b9cf-d63d-40bc-a167-d1685db14e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rut&quot;)</value>
      <webElementGuid>bc51892a-5c30-4a74-baae-a643c5bbcd36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rut']</value>
      <webElementGuid>d7756005-6105-4b19-a26e-91e1026c2e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='checknacional']/td[2]/input</value>
      <webElementGuid>973861db-4408-422a-883d-b263bb0cf989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>7277f516-a848-42c4-9d83-bbcfa755e587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'rut' and @name = 'rut' and @title = 'RUT sin puntos y con guión' and @placeholder = 'Ej: 12123123-2']</value>
      <webElementGuid>0b1389ab-c65c-470f-b5a9-4b0413bfdb1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
