<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputNombre</name>
   <tag></tag>
   <elementGuidId>97ffa0ae-69b7-4890-be4d-cd823d9d15bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nombres</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nombres']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#nombres</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05993a8a-89f1-40f7-a1f7-d12e1da09cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d3c4ff4b-7aac-4d94-af86-04657261de7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nombres</value>
      <webElementGuid>c9ec4149-7b59-48c7-ac8d-6d4aa22e844e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desplegable</value>
      <webElementGuid>aa80976b-d38b-44b8-86d5-06faa39d27b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nombres</value>
      <webElementGuid>d0efd929-f21e-4a52-8c61-323014ee2492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b6d79495-4e1d-4f72-a796-c444e9dabe3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validadorCaracteres(this.value, this.id)</value>
      <webElementGuid>690bc5a4-7d18-4cf0-a9c9-4a47b88e214e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nombres&quot;)</value>
      <webElementGuid>599235c9-d617-4579-9858-cabb97a8d847</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nombres']</value>
      <webElementGuid>9f61bc79-5791-4775-8038-604d95f4c65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form']/tbody/tr[4]/td/fieldset/div/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>5cb155bb-71be-4097-84fb-aeeb2a2c4437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>aa1b99da-5fb0-4353-8e2e-1418e4090bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nombres' and @id = 'nombres']</value>
      <webElementGuid>55031800-e221-40cb-b9b8-edb8d100cc9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
