<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_buttonAgregarApo</name>
   <tag></tag>
   <elementGuidId>a9759579-1cce-493f-ad98-94f4e2e45539</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(13) > td:nth-of-type(2) > input.boton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Matricular Alumno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Matricular Alumno&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4e9b79b-0251-4fe1-830a-11fba8e4bad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>baf7bf21-8ef0-419d-9780-82c8bd99b43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>boton</value>
      <webElementGuid>41dc66f2-ea22-4df9-b013-ce5e7a776aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Matricular Alumno</value>
      <webElementGuid>2c974fe2-7423-4990-80df-7e06b6ffd054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>vrut(0, 2025)</value>
      <webElementGuid>6c5d7131-fadf-43ec-a91f-ef3f9f77045a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal_apoderados&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/form[1]/table[@class=&quot;table agregar-apoderado&quot;]/tbody[1]/tr[13]/td[2]/input[@class=&quot;boton&quot;]</value>
      <webElementGuid>f717e528-f3a4-43a7-b73b-fba900fd5fbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Matricular Alumno']</value>
      <webElementGuid>e34c5eb2-0352-421f-ae2e-0a60ac6d68ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[13]/td[2]/input</value>
      <webElementGuid>e9b6f605-3200-444a-928c-c8f3185cc863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[13]/td[2]/input</value>
      <webElementGuid>14b2bae5-ea0f-4c35-8bff-2dcbca843107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>ab27276a-960a-4b5e-8aa9-d0d4b204e211</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
