<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputRutApoderado</name>
   <tag></tag>
   <elementGuidId>a8831ce1-ccff-49b5-9b76-67ecf4583773</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_rut</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apo_rut']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ej: 17960518-9/0300004&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c75c66c5-772e-47e1-b754-ef832890bfcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f687366-df1e-443d-aa8e-da395d020840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_rut</value>
      <webElementGuid>bdf003f5-66cc-44ad-9c85-fe47a607db72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_rut</value>
      <webElementGuid>d367f7bc-cb17-41e1-8635-5741dd51cb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>RUT sin puntos y con guión</value>
      <webElementGuid>03964cb1-6799-4edc-93fc-6b2f0e17b0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>543619b6-f6a5-4f8f-862e-d74559ffeb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>limpiarRut(this.value, 2)</value>
      <webElementGuid>327802b4-f022-41c2-bf04-fdafa67adebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>validarRut(this.value, 2)</value>
      <webElementGuid>ccfcfc96-623a-48cf-9b2d-d369a56408c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ej: 17960518-9/0300004</value>
      <webElementGuid>b4e87b1b-a3d6-4d60-b2c3-cf5dfaadacfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_rut&quot;)</value>
      <webElementGuid>fc5b91fd-ab83-4661-8266-3b1a45b29c10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apo_rut']</value>
      <webElementGuid>03b9d3d5-6320-4392-b773-767cf7a5e923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>ca295796-f6d8-4864-8e22-6ba97921914a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>5172545a-76c2-4a72-b53a-66036f03bfaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'apo_rut' and @name = 'apo_rut' and @title = 'RUT sin puntos y con guión' and @placeholder = 'Ej: 17960518-9/0300004']</value>
      <webElementGuid>66431b4b-81a5-4c5f-9c14-048ae686abf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
