<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputApellidoMApoderado</name>
   <tag></tag>
   <elementGuidId>d3c4ef55-3708-46cb-86f4-dc447bee0cb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_apm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apo_apm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#apo_apm</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61a92708-d720-4f49-bbc2-07443127b1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f95c7d5-b21a-4bad-89f1-5d624ccf0aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>35f04502-cab9-400d-98c4-8c789990cfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_apm</value>
      <webElementGuid>c693d003-5a1f-45fe-b337-5fc9f725f3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_apm</value>
      <webElementGuid>e2d49745-9ac7-45ba-aa95-017a57660c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_apm&quot;)</value>
      <webElementGuid>9b787ed2-9b9b-4e99-95b1-b817bd6860ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apo_apm']</value>
      <webElementGuid>4a5ff827-0c02-4eaf-ac48-0d617f260ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>d3f7f1d3-3373-40f7-a794-ee63d2c7954f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>8e4c414b-c755-4f51-a6ba-ba835aea0790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'apo_apm' and @name = 'apo_apm']</value>
      <webElementGuid>bd99af99-339e-4f6b-8ba7-05e571bd9afd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
