<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_checkVulnerable</name>
   <tag></tag>
   <elementGuidId>29b87f4b-c930-4445-bb60-f59f38acb11c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vulnerable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vulnerable']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#vulnerable</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a2288fe-fba7-44bc-b8bb-0f4097c745cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e4225cd8-396b-4a48-b103-af9c319768c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vulnerable</value>
      <webElementGuid>25bc78ba-96e8-401a-bd46-ce9fe65fa4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vulnerable</value>
      <webElementGuid>6262631f-093c-4cd3-900e-e9eaedd028d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vulnerable&quot;)</value>
      <webElementGuid>8be40beb-d2e0-4052-bf6c-4fd36d173705</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vulnerable']</value>
      <webElementGuid>5741a9b4-4204-40d9-af8d-f254144b6f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form_3']/tbody/tr[8]/td[2]/input</value>
      <webElementGuid>3a62ff0e-68f9-4792-a01c-59cd3bbf34de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr[8]/td[2]/input</value>
      <webElementGuid>20ec2759-cdf9-4e88-9cea-7882a55211e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'vulnerable' and @id = 'vulnerable']</value>
      <webElementGuid>4bf83142-1969-4d98-8ad5-694c200fa1ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
