<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputPreferente</name>
   <tag></tag>
   <elementGuidId>5b2e3e57-00ed-4dc7-8b77-b9a9b36a6fe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#preferente</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='preferente']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#preferente</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0447087-3306-481a-8d6b-0a583a08d4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>92bc6f44-5d82-4ac4-ba2c-a902a2eb3094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>preferente</value>
      <webElementGuid>a31e0e2d-b8c5-4b50-9ada-b2b645e4e4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>preferente</value>
      <webElementGuid>416afa05-1c5c-47be-a731-92d51bbff8e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preferente&quot;)</value>
      <webElementGuid>fa0c15d3-41d6-4159-8a9e-d58b9f6745a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='preferente']</value>
      <webElementGuid>e66f6130-e3fc-4333-8af9-c4d774827398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form_3']/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>7fd18541-139a-4ffe-b2ae-0b8458e04763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>78d9e04e-a374-4329-98f7-76c82fd69af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'preferente' and @id = 'preferente']</value>
      <webElementGuid>a33bf54c-6189-4d2d-ba04-e782f08c31aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
