<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputSangre</name>
   <tag></tag>
   <elementGuidId>cd3948f4-9933-4c46-8bd4-b71d179dd24f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#g_sangre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='g_sangre']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#g_sangre</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f229904-c717-45bc-b6e4-61588bb64af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6b3aa806-b1a9-4b93-813c-7a5b5ef21b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>g_sangre</value>
      <webElementGuid>ef203290-4054-44fd-8e51-927a48cdae74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g_sangre</value>
      <webElementGuid>5678c791-5f9a-4240-bb26-b1a816e42f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desplegable</value>
      <webElementGuid>4b0b43ff-a9dc-4963-9f7d-529392857cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>376e2b60-3405-4d36-a12f-438172b58b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validadorCaracteresComillas(this.value, this.id)</value>
      <webElementGuid>2aebd67f-7ec8-4bb0-b5b0-74c7e40a1dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g_sangre&quot;)</value>
      <webElementGuid>23a41316-7d56-43b2-85b6-d57e1e21857d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='g_sangre']</value>
      <webElementGuid>64eee6a5-1985-4454-b3cd-6f97fe8338ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form']/tbody/tr[4]/td/fieldset/div/table[2]/tbody/tr[14]/td[2]/input</value>
      <webElementGuid>3a33a83b-6249-45f1-bb48-63631471fbe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td[2]/input</value>
      <webElementGuid>c865bf0c-7d16-46bc-9e59-0bf1eea57cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'g_sangre' and @id = 'g_sangre']</value>
      <webElementGuid>388aa0c7-7fc3-411b-9c4e-b641bdb8cdd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
