<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_checkBecaIndigena</name>
   <tag></tag>
   <elementGuidId>19e994dc-43d1-4124-8091-a96fec8b1319</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#beca1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='beca1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#beca1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6945d3e8-4fc8-40d4-820b-34a7c1c6c6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>718c2fbb-d369-4a71-b6e8-626f68fb0e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>beca1</value>
      <webElementGuid>2a0d1738-b470-42b9-bc45-9bcad5268d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>34</value>
      <webElementGuid>344e97b3-b030-4df6-8d2c-218fd76dca30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;beca1&quot;)</value>
      <webElementGuid>c945aaf9-ac4f-4ced-a5f1-b205347b2c92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='beca1']</value>
      <webElementGuid>88490ae9-e370-4263-8551-2d6081a7fe3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='priotrabeca']/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>0bdd1ef7-b71c-43f9-8b91-cd52b9fab809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>a6c784cb-a067-4ceb-8b83-0d79afc69c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'beca1']</value>
      <webElementGuid>3983354f-8a53-404f-b623-25198d1ab1a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
