<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_radioButtonPasaporte</name>
   <tag></tag>
   <elementGuidId>998c3a3b-9407-4061-ad26-3edcaef7f116</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checknacionalidad2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checknacionalidad2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#checknacionalidad2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>decb55c5-ef95-4572-9082-a1db063d6de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2c9d1f56-5ace-48bb-86ab-1c7c3bbe88e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checknacionalidad</value>
      <webElementGuid>3c63a6a1-3901-4c2f-a3ff-9fad4a590c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checknacionalidad2</value>
      <webElementGuid>c711bdd4-e6a5-4c4e-8bf2-3210871c4bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>3347e964-88f2-4533-9dd4-7bf325d17b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>b8525c40-7a8c-4d8c-848a-58d9300b7264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checknacionalidad2&quot;)</value>
      <webElementGuid>6f2b4ed4-1484-4239-8f61-03dfac6afc87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checknacionalidad2']</value>
      <webElementGuid>dc1545e0-e16f-464b-af7c-1a83d06d3a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form']/tbody/tr[4]/td/fieldset/div/table/tbody/tr/td[2]/span[2]/input[2]</value>
      <webElementGuid>45622923-61cf-405a-9b9b-4e87cf7a104b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input[2]</value>
      <webElementGuid>27f82f4d-7519-47ca-a4ef-01421a39c536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'checknacionalidad' and @id = 'checknacionalidad2']</value>
      <webElementGuid>5e623fd4-260b-4b87-b675-6cff78461f00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
