<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputNMatricula</name>
   <tag></tag>
   <elementGuidId>e21b7421-f18e-4064-8c43-218dd64e1e6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#n_matricula</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='n_matricula']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#n_matricula</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fe24360-f723-431e-bc59-dd2fc9dd91d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>37bb2c96-f97a-4f49-975e-898eca252a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>n_matricula</value>
      <webElementGuid>046bed75-9183-481d-aca1-61bc15b8e380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>n_matricula</value>
      <webElementGuid>b813964d-d418-4df6-b221-87d7ec63a0a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>cf2020f0-616f-4096-ab55-e0a969f690a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n_matricula&quot;)</value>
      <webElementGuid>8baedae9-4fe2-4e4c-b1fe-8f0e6aafa0ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='n_matricula']</value>
      <webElementGuid>6a894bac-321a-485c-b4aa-2275d3666adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form_2']/tbody/tr/td[2]/input</value>
      <webElementGuid>e647f00f-be47-4620-9ef6-5bbf4dfda52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/fieldset/div/table[2]/tbody/tr/td[2]/input</value>
      <webElementGuid>0580a929-3bfd-4c43-a977-6347d4c8d5e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'n_matricula' and @id = 'n_matricula']</value>
      <webElementGuid>597ecaca-839d-44c9-b59e-cea77bb347af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
