<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputCoPostal</name>
   <tag></tag>
   <elementGuidId>eec89ba1-3622-4683-ae5d-9f0694552389</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#codigoPostal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='codigoPostal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#codigoPostal</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57975d48-b550-4a40-a190-1c837c07ee8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>661f6c4f-6163-403a-942a-fb90ee1d1f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desplegable</value>
      <webElementGuid>2df96510-680d-4b4b-85cb-e4dec40f18b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>codigoPostal</value>
      <webElementGuid>3d26291b-758c-482c-889d-93323f0b9d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>codigoPostal</value>
      <webElementGuid>83159399-652c-42c3-be7f-a454924ef8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validarNumeros(this,1,1);</value>
      <webElementGuid>d685da40-94ee-4b6c-9326-51a9957873c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;codigoPostal&quot;)</value>
      <webElementGuid>ca4ebf37-fbc4-4833-94d0-ecef0e5ea227</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='codigoPostal']</value>
      <webElementGuid>302c408c-4599-4bfc-b1e9-cb6e54fa25b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form']/tbody/tr[4]/td/fieldset/div/table[2]/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>f015303f-db24-4b39-b016-ab414a2fff16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>b28eb40f-1f67-4646-b67c-ae07ca8f30b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'codigoPostal' and @id = 'codigoPostal']</value>
      <webElementGuid>83bcf51c-e840-44d5-984b-9bd63ea60702</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
