<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_selectComunaApo</name>
   <tag></tag>
   <elementGuidId>5d47669a-19ac-4ce2-acbe-7b9a0d90d12d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_com</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='apo_com']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#apo_com</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>416d292b-d46e-42f3-866f-d17e0a9ff938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>31027472-3798-4911-82a0-f23361b82f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_com</value>
      <webElementGuid>46a03cb4-9176-469e-bc9c-1909043d1fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_com</value>
      <webElementGuid>89d622b6-aefd-4cc6-bcaf-afcee7218a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>            Sin Datos            
            </value>
      <webElementGuid>e6c1c5d4-3e54-4b87-b0ae-bf1987f9dc74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_com&quot;)</value>
      <webElementGuid>fdd98592-cf19-4c9b-b8ab-84a3fac8589f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='apo_com']</value>
      <webElementGuid>b4e8f465-f130-4e7c-a54e-90001d5d3ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[7]/td[3]/select</value>
      <webElementGuid>af5468f7-7a5c-4bc1-abc4-a65a01d0977d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Codigo postal:'])[1]/preceding::select[1]</value>
      <webElementGuid>11266984-8b0a-482d-9d38-b9aaf8250156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail:'])[1]/preceding::select[1]</value>
      <webElementGuid>078114f4-ae5e-45c6-a9df-b65fdb755b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/select</value>
      <webElementGuid>a31b6029-b143-42cd-9247-81077b7c54c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'apo_com' and @name = 'apo_com' and (text() = '            Sin Datos            
            ' or . = '            Sin Datos            
            ')]</value>
      <webElementGuid>ac1aeaa6-0318-45b3-9d93-1b7bf6cc3609</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
