<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_selectDocumentoApoderado</name>
   <tag></tag>
   <elementGuidId>29da51d1-5d11-47eb-8c74-0b034a05efe0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_doc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='apo_doc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#apo_doc</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>23791c93-b61f-4619-ae53-1f395f742e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_doc</value>
      <webElementGuid>73061d95-be4a-49cf-9247-7c130f0548d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>abb380a1-0c28-446a-8468-aa443e854746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_doc</value>
      <webElementGuid>1ec54c0b-502a-43f5-bf89-2843d162350e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>verificarRP()</value>
      <webElementGuid>ea4630a3-135a-45e3-b894-a5e625a5970f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                            RUN
                                                                                Pasaporte
                                                                        </value>
      <webElementGuid>b84a3a4f-eda9-4406-97a7-4ddccdc6ddac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_doc&quot;)</value>
      <webElementGuid>98fe9daa-5846-493c-87e8-e1643b89d779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='apo_doc']</value>
      <webElementGuid>10605073-9a29-4862-a0b0-74d1fb9b8a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[3]/td/select</value>
      <webElementGuid>bc0e6104-4489-41d9-9675-8ce7520db999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agregar foto:'])[1]/following::select[1]</value>
      <webElementGuid>d1222a43-549f-424c-8462-8167f42520c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[11]/preceding::select[1]</value>
      <webElementGuid>25764483-d046-4ebb-a42a-18d679f01d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[3]/td/select</value>
      <webElementGuid>b946d7e9-0e92-4487-9dc8-aaa4e7589be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'apo_doc' and @name = 'apo_doc' and (text() = '
                                                                            RUN
                                                                                Pasaporte
                                                                        ' or . = '
                                                                            RUN
                                                                                Pasaporte
                                                                        ')]</value>
      <webElementGuid>405c070a-66a9-487c-a389-db6c3cedbc21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
