<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_checkPAE</name>
   <tag></tag>
   <elementGuidId>821815b9-7312-444d-baa0-047443ab02fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OtrBen1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OtrBen1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;PAE&quot;s] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffe4bb8b-d513-4c2c-a969-aa4f1c7f82d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>df0fad10-4035-4048-8fde-5b8bd2976258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OtrBen1</value>
      <webElementGuid>821782aa-84c2-4e40-b8e7-3a245f8b9cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OtrBen1&quot;)</value>
      <webElementGuid>4178cbe6-1b9a-4d9b-9a13-bad9a35c95a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OtrBen1']</value>
      <webElementGuid>0944b32b-42c2-489f-9d56-d35c6ce08141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='otros_beneficios']/table/tbody/tr/td/input</value>
      <webElementGuid>37185774-c230-4cea-afd1-b63441f579ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/table/tbody/tr/td/input</value>
      <webElementGuid>a21f73c5-7a2f-4778-9444-dc3aeb4c036a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'OtrBen1']</value>
      <webElementGuid>a1f203d6-bb28-4bd4-94b1-947e586ea689</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
