<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_selectEstadoCivilApo                                                                   Casado(a)                                                                                Separado(a)</name>
   <tag></tag>
   <elementGuidId>05261dac-e776-4ec6-a024-94992b2e4c54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_est</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='apo_est']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#apo_est</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2360eba3-185a-4a6a-8232-9717565209a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_est</value>
      <webElementGuid>11292c66-43d6-4fc1-98df-168d7fa3337e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>84a995bd-293c-441a-bfa4-1d7d47727ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_est</value>
      <webElementGuid>5d331ad5-d69f-401a-b40c-7fc538641171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                            Soltero (a)
                                                                                Casado(a)
                                                                                Separado(a)
                                                                                Viudo(a)
                                                                                Divorciado(a)
                                                                                Conviviente Civil
                                                                        </value>
      <webElementGuid>000729ee-e349-436e-98e0-ca16ab6ec26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_est&quot;)</value>
      <webElementGuid>72960a61-0af1-45ff-9e1c-5eb66fa11115</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='apo_est']</value>
      <webElementGuid>32c267ca-8c0f-47d7-981a-f0319deb8acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[3]/td[4]/select</value>
      <webElementGuid>931053e7-3bee-4026-b89c-76138177d4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/select</value>
      <webElementGuid>633332b3-ff61-44be-aadf-f854fa7f61e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'apo_est' and @name = 'apo_est' and (text() = '
                                                                            Soltero (a)
                                                                                Casado(a)
                                                                                Separado(a)
                                                                                Viudo(a)
                                                                                Divorciado(a)
                                                                                Conviviente Civil
                                                                        ' or . = '
                                                                            Soltero (a)
                                                                                Casado(a)
                                                                                Separado(a)
                                                                                Viudo(a)
                                                                                Divorciado(a)
                                                                                Conviviente Civil
                                                                        ')]</value>
      <webElementGuid>8b988ad3-0062-4212-bb59-3a6765d268f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
