<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_codigoPostalApo</name>
   <tag></tag>
   <elementGuidId>e1ae5447-bd5e-401d-81e1-b3ff1fb95684</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_postal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apo_postal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;1234567&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ad3c781-8b28-49d2-8e1a-69f4053eee98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0c5f09a7-9054-49b5-82a8-7b6ffde6cb10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ceaea8a3-2db8-48b0-81be-ec5a49bd14af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_postal</value>
      <webElementGuid>0df65183-72fd-4592-aa6d-1da01a43c705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_postal</value>
      <webElementGuid>96f83926-a5ee-44e6-aa7b-a85ff343f68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1234567</value>
      <webElementGuid>a97f7117-990b-4775-8626-e2c7754a7bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validarNumeros(this,2,1);</value>
      <webElementGuid>d6b8f024-7526-4f59-9797-e82b57f185fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_postal&quot;)</value>
      <webElementGuid>b725f7ea-fbf8-44f5-bd0d-4ce75e22ae11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apo_postal']</value>
      <webElementGuid>679057b1-05b2-49bb-b4f6-e98350cadae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[7]/td[4]/input</value>
      <webElementGuid>745a265e-a55b-4cbb-906a-1d3aee238d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[4]/input</value>
      <webElementGuid>67475a17-173e-4aa2-b3d9-10ff32033143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'apo_postal' and @name = 'apo_postal' and @placeholder = '1234567']</value>
      <webElementGuid>afb1f662-de72-4d1e-a46d-b2347ecd7592</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
