<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputAnioIngreso</name>
   <tag></tag>
   <elementGuidId>6bd04091-ff75-4185-89bb-7bd3836a027e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#anio_ingreso</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='anio_ingreso']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#anio_ingreso</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e831315b-52fc-40ac-bb5e-5f09c6ab59d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>441c20c1-d5a8-44f3-90f6-52b5dacb71d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>04c686d3-b2f5-4fe3-a5e2-9b67cb6af409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>anio_ingreso</value>
      <webElementGuid>cdd68aec-82d4-4772-8595-04b23dc7ae08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anio_ingreso</value>
      <webElementGuid>a3fc733c-7876-4c0a-a214-fd0312094faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>ac8b80be-a9ed-42d3-9fd4-7ec73f167a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anio_ingreso&quot;)</value>
      <webElementGuid>a1bf2ef0-0666-4afa-bbf6-0ba8c026e735</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='anio_ingreso']</value>
      <webElementGuid>42c9117a-204a-4703-a73d-9544c69aceae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form_2']/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>50499007-70c9-40b3-97ef-99f403409f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/fieldset/div/table[2]/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>6e5d9d1f-60b6-4dbc-a068-c0437af39818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'anio_ingreso' and @id = 'anio_ingreso']</value>
      <webElementGuid>89d3edc3-109a-4122-8052-e78b840a67bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
