<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_checkPrioritario</name>
   <tag></tag>
   <elementGuidId>98f2ad43-7f84-4323-9793-b143d4611e1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prioritario</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prioritario']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#prioritario</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ec34c7a-de65-4238-848e-00cfe3899501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>58fb1c23-de09-4d7e-a7e6-5cd9d5b7312d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>prioritario</value>
      <webElementGuid>78fea11d-4f03-47bb-a246-fd1be6a6aa6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prioritario</value>
      <webElementGuid>d0fc892c-4437-47d3-946d-773d4384b58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>/*funcprioritario()*/</value>
      <webElementGuid>39f61492-7af1-42b8-ad40-eb7299998d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prioritario&quot;)</value>
      <webElementGuid>6f060ed2-cc38-4811-b0f1-c69f9117643f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prioritario']</value>
      <webElementGuid>b50d8ce3-5be6-4463-8043-b1d8a2cc57f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form_3']/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>e62701a9-80e7-4636-9678-5dad186583e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>08cccaef-4a49-4412-87d0-8d9b47a01f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'prioritario' and @id = 'prioritario']</value>
      <webElementGuid>6e914b5f-b0ab-4171-a4ef-7f82dac859f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
