<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_checkRepite1Medio</name>
   <tag></tag>
   <elementGuidId>a90fa60f-3bcf-4a7e-974d-de3515f05e1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chk_cr_11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chk_cr_11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#chk_cr_11</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0925b657-7856-4831-b392-2212d0a1f829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7fcb0448-f5b6-416d-ad8f-a4dad259ad51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chk_cr_11</value>
      <webElementGuid>81e38754-0af7-4214-87b4-3f7bb6c51ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chk_cr_11&quot;)</value>
      <webElementGuid>05c4d444-947a-4701-b52e-2837002b1e14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chk_cr_11']</value>
      <webElementGuid>cc89a905-b59c-46f8-b986-19eff3a38b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='repittegrd']/td[3]/table/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>4e209a46-1c87-4ac8-8536-8b42da38f133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/input</value>
      <webElementGuid>7eec05df-e34d-446e-9ab3-173ca806428e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'chk_cr_11']</value>
      <webElementGuid>d55d183e-f751-4c25-92ed-6a8d000f031a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
