<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_selectViveCon                                                                                   Padres                                                                                     Pap</name>
   <tag></tag>
   <elementGuidId>d17baeb2-620a-4297-a998-8a22fe74d8ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vive_con</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='vive_con']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#vive_con</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>02cc09e1-deca-4792-9fb2-d553697a4105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vive_con</value>
      <webElementGuid>0865958d-2bbb-448b-bc9a-01aa9bbc6ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vive_con</value>
      <webElementGuid>37a16ad7-82b6-41eb-893a-584ea83343b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>MostrarViveOtros(this.value)</value>
      <webElementGuid>93f5b47f-8d0a-4bcf-a750-783e43407b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>c1191d53-7893-4c43-bc96-60496af73dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                     No especifica                            
                                                         Padres                            
                                                         Papá                            
                                                         Mamá                            
                                                         Otros                            
                                                </value>
      <webElementGuid>6724b8bb-e406-46d5-a693-b5cd01295810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vive_con&quot;)</value>
      <webElementGuid>bdfc92e8-17d5-4446-b0bd-e61cebf6213e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='vive_con']</value>
      <webElementGuid>1b7e6878-fea5-4f49-8b0b-8b6714ff5b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='new_tabla_apoderados']/fieldset/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>c87d3c54-15fd-4a9a-abc0-c4a9dcaca1d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[51]/following::select[1]</value>
      <webElementGuid>7c4324d6-0163-4540-b466-5106ba976316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alumno vive con'])[1]/following::select[1]</value>
      <webElementGuid>6f7dc2a4-882b-4e5a-88c6-6f6f32071072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N° de personas del grupo familiar'])[1]/preceding::select[1]</value>
      <webElementGuid>0fe807e3-baed-436f-bb53-57a0cc0ed3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[52]/preceding::select[1]</value>
      <webElementGuid>a609992e-6e88-4161-b481-15013ecfb017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/fieldset/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>a0240ef1-cf4a-4b79-a7f3-9559e60de434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'vive_con' and @id = 'vive_con' and (text() = '
                                                     No especifica                            
                                                         Padres                            
                                                         Papá                            
                                                         Mamá                            
                                                         Otros                            
                                                ' or . = '
                                                     No especifica                            
                                                         Padres                            
                                                         Papá                            
                                                         Mamá                            
                                                         Otros                            
                                                ')]</value>
      <webElementGuid>8159ac21-e69c-443a-99b7-1115f58fbfa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
