<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputDireccionApo</name>
   <tag></tag>
   <elementGuidId>0f73dada-d641-4638-b686-b99d959d23c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_dir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apo_dir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Calle 123&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a786051-fd72-4f50-b430-d8f12328586a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d669a9a2-3129-464b-9fb0-958b9eceadd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_dir</value>
      <webElementGuid>0e2f806d-1406-4d6f-9274-a0c68b2f25c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f6f56ef4-ba2a-4cb4-bf94-ec3dc9e2715f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_dir</value>
      <webElementGuid>b086e974-d9a3-4b34-95c8-3fab1ba8dc13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Calle 123</value>
      <webElementGuid>937c4497-0784-4526-9f93-60ebcd746d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_dir&quot;)</value>
      <webElementGuid>a3ae3aab-3ca6-4932-b0a7-ff1208a12261</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apo_dir']</value>
      <webElementGuid>38221b68-6571-4c3c-be93-d45503c14cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[7]/td/input</value>
      <webElementGuid>f5ecec27-cbb4-4189-b587-7d0704d89f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[7]/td/input</value>
      <webElementGuid>e6877792-47b2-440c-a04f-baf994036d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'apo_dir' and @name = 'apo_dir' and @placeholder = 'Calle 123']</value>
      <webElementGuid>dc9000fa-f005-422b-a6a5-0ba42b1ea95e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
