<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_checkRepite3Medio</name>
   <tag></tag>
   <elementGuidId>5e123d26-c962-4a42-974d-8fd225426c84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chk_cr_13</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chk_cr_13']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#chk_cr_13</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee5a4230-c4a8-452b-9ed9-16d70a269894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9131cfc9-7aff-4d16-99b1-4ae1b4c53f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chk_cr_13</value>
      <webElementGuid>bdd649ca-b49e-4e20-8caa-e1475ad2718c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chk_cr_13&quot;)</value>
      <webElementGuid>7985c696-7dbc-40b2-af4c-582834334602</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chk_cr_13']</value>
      <webElementGuid>0ae34714-3444-4c23-8dff-9cffb4c06585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='repittegrd']/td[3]/table/tbody/tr[2]/td[6]/input</value>
      <webElementGuid>30020247-6605-4b21-ab38-44a0a3c4b913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]/input</value>
      <webElementGuid>2b3e4406-1b74-4005-9d9a-6b6308969b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'chk_cr_13']</value>
      <webElementGuid>ac882d62-38a5-48ee-8f07-043922f546f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
