<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputNombreApoderado</name>
   <tag></tag>
   <elementGuidId>6f3d9d3a-c041-48bf-9971-ed52ef0a14d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_nom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apo_nom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#apo_nom</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>058928cc-2777-4a5b-b63a-425b0ef64194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>37853c43-c511-4acd-bac9-ee3c62c058f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9757a781-be24-47c6-9785-6d1a5b9759b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_nom</value>
      <webElementGuid>41b81831-4383-4ec3-8b87-8dc23fe5b09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_nom</value>
      <webElementGuid>e3beae98-b6f3-4842-b1bc-996760f79950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_nom&quot;)</value>
      <webElementGuid>696c5ba6-0373-4013-9277-9c4ffb8c569f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apo_nom']</value>
      <webElementGuid>200da038-3448-43b4-9858-a6f61d389391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[2]/td/input</value>
      <webElementGuid>c03994f2-c216-416e-bfc0-64a63a7c7217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[2]/td/input</value>
      <webElementGuid>b930b2b0-d586-4cb9-8711-2e9226442f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'apo_nom' and @name = 'apo_nom']</value>
      <webElementGuid>8c64e2a7-c88b-45dc-ac92-6d541fbb5fac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
