<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_radioMasculinoApoderado</name>
   <tag></tag>
   <elementGuidId>e76fcb1a-7ea3-450f-92f6-6712ed359c4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_gen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apo_gen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#apo_gen >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af4b1175-e936-4a9b-80a7-23a1cb0438b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c2d03f8a-7026-4c30-a7d3-e2d7501b0982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d6afd61a-f1e6-477d-9e59-7f8ef3d0f14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_gen</value>
      <webElementGuid>6b9b3946-7236-4717-8875-ec08cbccda51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_gen</value>
      <webElementGuid>6a791d65-779c-4929-8b12-7ddc7b16cf05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal_apoderados&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/form[1]/table[@class=&quot;table agregar-apoderado&quot;]/tbody[1]/tr[3]/td[3]/input[@id=&quot;apo_gen&quot;]</value>
      <webElementGuid>eaa4bd19-eb6b-41db-bc81-fa91708dce06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apo_gen']</value>
      <webElementGuid>82d8c85c-e494-405b-b25e-91af20a8a842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[3]/td[3]/input</value>
      <webElementGuid>c1de0448-694a-4b59-83e3-dcae35f40a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[3]/td[3]/input</value>
      <webElementGuid>ba2fbdf5-2360-4491-bbf6-069259475ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'apo_gen' and @name = 'apo_gen']</value>
      <webElementGuid>e0fb1d49-55d5-4e9d-a4ea-b37a8baa8402</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
