<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_checkApoFinanciero</name>
   <tag></tag>
   <elementGuidId>8bf62319-77bb-4731-a328-23659b959e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_fin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apo_fin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#apo_fin</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11d64bee-8c5b-4f34-a8bb-b70ea6943b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b68380d3-63c5-42db-9d4f-e16a98e12a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_fin</value>
      <webElementGuid>1e16271d-a1db-4131-adf8-3af27c164003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_fin</value>
      <webElementGuid>5c85d8d2-3997-44ac-aa6d-eec4b7f96ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c7cff1b7-e315-41db-baeb-f229eb68eb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_fin&quot;)</value>
      <webElementGuid>8c7c2632-cbd4-474f-ae53-0173aa46da5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apo_fin']</value>
      <webElementGuid>bed9535b-c780-4f6d-bd39-b947a0d35e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[11]/td[4]/input</value>
      <webElementGuid>1fa11889-d3ab-472b-a730-c20a90eceec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td[4]/input</value>
      <webElementGuid>bf5b9b56-7720-467f-8a59-5ca6026fe73f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'apo_fin' and @name = 'apo_fin']</value>
      <webElementGuid>482d87b5-93f4-4251-bf3a-27ad9b67a4fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
