<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_selectNacionalidadApo                                                                                                            Extranjera</name>
   <tag></tag>
   <elementGuidId>16978033-50f8-44fb-a155-9c84fff917f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'apo_nacionalidad' and @id = 'apo_nacionalidad' and (text() = '                                        
                                            Chilena                                                                                
                                            Extranjera                                                                                
                                            Venezolana                                                                                
                                            Alemana                                                                                
                                            Argentina                                                                                
                                            Boliviana                                                                                
                                            Brasileña                                                                                
                                            China                                                                                
                                            Colombiana                                                                                
                                            Coreana                                                                                
                                            Costarricense                                                                                
                                            Cubana                                                                                
                                            Ecuatoriana                                                                                
                                            Española                                                                                
                                            Estadounidense                                                                                
                                            Francesa                                                                                
                                            Haitiana                                                                                
                                            Hondureña                                                                                
                                            Hindú                                                                                
                                            Italiana                                                                                
                                            Japonesa                                                                                
                                            Mexicana                                                                                
                                            Paraguaya                                                                                
                                            Peruana                                                                                
                                            Puertorriqueña                                                                                
                                            Dominicana                                                                                
                                            Ucraniana                                                                                
                                            Uruguaya                                                                        ' or . = '                                        
                                            Chilena                                                                                
                                            Extranjera                                                                                
                                            Venezolana                                                                                
                                            Alemana                                                                                
                                            Argentina                                                                                
                                            Boliviana                                                                                
                                            Brasileña                                                                                
                                            China                                                                                
                                            Colombiana                                                                                
                                            Coreana                                                                                
                                            Costarricense                                                                                
                                            Cubana                                                                                
                                            Ecuatoriana                                                                                
                                            Española                                                                                
                                            Estadounidense                                                                                
                                            Francesa                                                                                
                                            Haitiana                                                                                
                                            Hondureña                                                                                
                                            Hindú                                                                                
                                            Italiana                                                                                
                                            Japonesa                                                                                
                                            Mexicana                                                                                
                                            Paraguaya                                                                                
                                            Peruana                                                                                
                                            Puertorriqueña                                                                                
                                            Dominicana                                                                                
                                            Ucraniana                                                                                
                                            Uruguaya                                                                        ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#apo_nacionalidad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='apo_nacionalidad']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#apo_nacionalidad</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bf161a54-1c9d-482c-95ae-de60461c6dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0eeb1384-eb57-41c1-8843-6e6f6b127dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_nacionalidad</value>
      <webElementGuid>0f71a584-b0fb-42e3-8c1f-07c1daa47687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_nacionalidad</value>
      <webElementGuid>0c9b675f-3ab7-446f-85ee-c8ccbc667f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>6470d8ea-cf85-4ba3-a19a-0ca2f624be91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>                                        
                                            Chilena                                                                                
                                            Extranjera                                                                                
                                            Venezolana                                                                                
                                            Alemana                                                                                
                                            Argentina                                                                                
                                            Boliviana                                                                                
                                            Brasileña                                                                                
                                            China                                                                                
                                            Colombiana                                                                                
                                            Coreana                                                                                
                                            Costarricense                                                                                
                                            Cubana                                                                                
                                            Ecuatoriana                                                                                
                                            Española                                                                                
                                            Estadounidense                                                                                
                                            Francesa                                                                                
                                            Haitiana                                                                                
                                            Hondureña                                                                                
                                            Hindú                                                                                
                                            Italiana                                                                                
                                            Japonesa                                                                                
                                            Mexicana                                                                                
                                            Paraguaya                                                                                
                                            Peruana                                                                                
                                            Puertorriqueña                                                                                
                                            Dominicana                                                                                
                                            Ucraniana                                                                                
                                            Uruguaya                                                                        </value>
      <webElementGuid>9faf667b-152a-45eb-878d-26be1d63c54f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_nacionalidad&quot;)</value>
      <webElementGuid>ea3239e3-6cb2-4f41-bb8c-fc43dbf5b4ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='apo_nacionalidad']</value>
      <webElementGuid>56c833d1-4c23-450b-ad07-e035d15c7936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[4]/td/select</value>
      <webElementGuid>e048ae2f-6677-4ac6-8ed1-2ef9be16d8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos de contacto'])[2]/preceding::select[1]</value>
      <webElementGuid>ff674bda-6124-4535-8bad-73c8e1fa862a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dirección:'])[1]/preceding::select[1]</value>
      <webElementGuid>90f1ba54-04a6-4595-8f76-f8a3b59c666b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[4]/td/select</value>
      <webElementGuid>ddb9fb56-deb4-4c97-996f-5bb7e86f20fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'apo_nacionalidad' and @id = 'apo_nacionalidad' and (text() = '                                        
                                            Chilena                                                                                
                                            Extranjera                                                                                
                                            Venezolana                                                                                
                                            Alemana                                                                                
                                            Argentina                                                                                
                                            Boliviana                                                                                
                                            Brasileña                                                                                
                                            China                                                                                
                                            Colombiana                                                                                
                                            Coreana                                                                                
                                            Costarricense                                                                                
                                            Cubana                                                                                
                                            Ecuatoriana                                                                                
                                            Española                                                                                
                                            Estadounidense                                                                                
                                            Francesa                                                                                
                                            Haitiana                                                                                
                                            Hondureña                                                                                
                                            Hindú                                                                                
                                            Italiana                                                                                
                                            Japonesa                                                                                
                                            Mexicana                                                                                
                                            Paraguaya                                                                                
                                            Peruana                                                                                
                                            Puertorriqueña                                                                                
                                            Dominicana                                                                                
                                            Ucraniana                                                                                
                                            Uruguaya                                                                        ' or . = '                                        
                                            Chilena                                                                                
                                            Extranjera                                                                                
                                            Venezolana                                                                                
                                            Alemana                                                                                
                                            Argentina                                                                                
                                            Boliviana                                                                                
                                            Brasileña                                                                                
                                            China                                                                                
                                            Colombiana                                                                                
                                            Coreana                                                                                
                                            Costarricense                                                                                
                                            Cubana                                                                                
                                            Ecuatoriana                                                                                
                                            Española                                                                                
                                            Estadounidense                                                                                
                                            Francesa                                                                                
                                            Haitiana                                                                                
                                            Hondureña                                                                                
                                            Hindú                                                                                
                                            Italiana                                                                                
                                            Japonesa                                                                                
                                            Mexicana                                                                                
                                            Paraguaya                                                                                
                                            Peruana                                                                                
                                            Puertorriqueña                                                                                
                                            Dominicana                                                                                
                                            Ucraniana                                                                                
                                            Uruguaya                                                                        ')]</value>
      <webElementGuid>9c89be68-23d1-4b7c-9bac-87b27cce7fd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
