<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputCelularApo</name>
   <tag></tag>
   <elementGuidId>ddbf40bf-0380-469f-92bb-4f656ecdb986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_cel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apo_cel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Celular: +56&quot;i] >> internal:attr=[placeholder=&quot;98765432&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d44c4b3-bb93-44f1-8a15-47d43853113d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>23038a29-dae8-4ee1-8fe5-2f0db6a1be75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_cel</value>
      <webElementGuid>5bf7aefa-657d-4c3d-9d9b-8014aacd5c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_cel</value>
      <webElementGuid>1ec91b75-1a38-4a49-a22c-76904ac07fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>98765432</value>
      <webElementGuid>299a2cbf-027a-4c66-b00b-5f13397197cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if ((event.keyCode &lt; 48) || (event.keyCode > 57)) event.returnValue = false;</value>
      <webElementGuid>6f5d976f-9c77-4bed-bbb9-485ba448b12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>fc13e701-eeed-4725-ac1d-cb07101513d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>bee08dae-3133-4a7f-bed0-48fa391d79ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validarNumeros(this,3);</value>
      <webElementGuid>f7523f93-6364-49e4-ada7-7d67e0e374d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_cel&quot;)</value>
      <webElementGuid>2a306446-0a91-403a-b4e3-e0cde4cad4d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apo_cel']</value>
      <webElementGuid>baabc86d-2c0f-49e9-84de-c50637bbe8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[8]/td[2]/div/div[2]/input</value>
      <webElementGuid>7ba18b8f-f5bd-4e58-8d52-0de4d71b6580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div[2]/input</value>
      <webElementGuid>94f91a3c-1d70-4017-a4a9-1ee8f40c4640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'apo_cel' and @name = 'apo_cel' and @placeholder = '98765432']</value>
      <webElementGuid>30ea4d9a-b980-40bc-9780-3270c094ad95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
