<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_selectParentescoApoderado</name>
   <tag></tag>
   <elementGuidId>0fc7f666-9900-4cb0-a0a4-bc304ea49e15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_par</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='apo_par']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#apo_par</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>087ac375-2929-4c82-9a4b-80c165180fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8460f8de-4430-4a26-b665-7bf518897707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_par</value>
      <webElementGuid>7846d9e1-4957-4327-9824-e932cce11a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_par</value>
      <webElementGuid>5196d3f6-14e6-4f46-9a43-ebf4c94a1e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                            Padre
                                                                                Madre
                                                                                Abuelo(a)
                                                                                Hermano(a)
                                                                                Tio(a)
                                                                                Primo(a)
                                                                                Sin definir
                                                                        </value>
      <webElementGuid>53753fd7-1392-4bf1-824f-e2378a785fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_par&quot;)</value>
      <webElementGuid>e5352735-5beb-479b-8687-f77c475eabe6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='apo_par']</value>
      <webElementGuid>4f596343-83cd-46d2-b275-38ff671981ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[3]/td[5]/select</value>
      <webElementGuid>30d56307-ab7c-46f4-a6e3-87490abf5bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos de contacto'])[2]/preceding::select[2]</value>
      <webElementGuid>c3dfe207-c1d4-48c4-88ba-ead1a0958cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/select</value>
      <webElementGuid>05be42ee-43ba-43d8-bb53-bbe143675b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'apo_par' and @name = 'apo_par' and (text() = '
                                                                            Padre
                                                                                Madre
                                                                                Abuelo(a)
                                                                                Hermano(a)
                                                                                Tio(a)
                                                                                Primo(a)
                                                                                Sin definir
                                                                        ' or . = '
                                                                            Padre
                                                                                Madre
                                                                                Abuelo(a)
                                                                                Hermano(a)
                                                                                Tio(a)
                                                                                Primo(a)
                                                                                Sin definir
                                                                        ')]</value>
      <webElementGuid>e9517464-850e-4d2c-ab7d-98668ebfb4cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
