<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputNhermanosColegio</name>
   <tag></tag>
   <elementGuidId>f70f3be6-e580-4991-883e-d9f674029528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#n_dhmec</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='n_dhmec']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#n_dhmec</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fdaecc2-3aa4-49e0-be58-79a2942ce3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bf4dbbdf-9b17-4d2f-ba3f-38e0d3f0d3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>41</value>
      <webElementGuid>bc44ed9b-65a8-4afd-a307-5a378d53fa9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>72378b78-1d6b-4712-97ba-443fdc06fb4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>n_dhmec</value>
      <webElementGuid>9dc73d29-404d-4560-bbd5-20ed17f62d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if ((event.keyCode &amp; lt; 48) || (event.keyCode &amp; gt; 57)) event.returnValue = false;</value>
      <webElementGuid>dea5a5f1-c0cb-4cfe-b8cc-91cdf68bf820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>330cd81e-a3c3-4ea6-8064-cacf6f80b773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n_dhmec&quot;)</value>
      <webElementGuid>85898bac-301a-4f38-8277-a05754f5dfe0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='n_dhmec']</value>
      <webElementGuid>62e4a6a2-09ec-4765-80fe-7883019ae0e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='new_tabla_apoderados']/fieldset/div/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>01d282f8-c777-42d9-bfef-31ec58a73e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/fieldset/div/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>163b5209-24d0-4173-a5ba-eded691eac49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'n_dhmec']</value>
      <webElementGuid>aad2e74a-8bea-45b2-88d6-208ef912723b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
