<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_radioButtonMasculino</name>
   <tag></tag>
   <elementGuidId>9f652478-af51-4a09-9c6e-ae5a6eac0992</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#genero</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='genero']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#genero >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8a5b2d3-2dde-4c2a-951e-d64034932424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a2b51f13-23c1-4d71-aff9-64bbf06ca0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>genero</value>
      <webElementGuid>dffcb8d3-a65d-4d9b-ab83-57bd12659232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>genero</value>
      <webElementGuid>6355ea5c-1775-4c3a-adfc-b5c493575edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bb32ddc3-4b30-42b8-99a0-eb691d0b60c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>234e180f-5f92-4d89-92a0-f176a5663c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_form&quot;)/tbody[1]/tr[4]/td[1]/fieldset[@class=&quot;fieldset-matricula&quot;]/div[@class=&quot;tablas-matricula&quot;]/table[@class=&quot;tbl-matricula-1&quot;]/tbody[1]/tr[7]/td[@class=&quot;input-genero&quot;]/span[2]/input[@id=&quot;genero&quot;]</value>
      <webElementGuid>f5854c08-3b72-4613-840e-120b074e024a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='genero']</value>
      <webElementGuid>fa8c815f-bfb3-493c-977d-052eca8e7aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form']/tbody/tr[4]/td/fieldset/div/table/tbody/tr[7]/td[2]/span[2]/input</value>
      <webElementGuid>3e1e9931-5658-46fa-84c9-bdaaed09524c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/span[2]/input</value>
      <webElementGuid>d936c7bb-ffa9-45b7-9262-5d13e154b97d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'genero' and @id = 'genero']</value>
      <webElementGuid>68dbe992-ec89-41de-88a2-5d85e628b4c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
