<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputEnfermedad</name>
   <tag></tag>
   <elementGuidId>b5b1ffaf-b130-4a01-965f-17b25d23c69d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#enfermedades</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='enfermedades']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Especifica enfermedad y tratamiento&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>121d7685-89e5-44d9-807e-6cdae6fff5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Especifica enfermedad y tratamiento</value>
      <webElementGuid>5a91f34f-0d6a-4355-adfc-5973a041d5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>enfermedades</value>
      <webElementGuid>3e2a7782-2064-4e61-bd19-2d0bcd40393d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>fa768a24-9f10-4907-8f94-5e5838bc975f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validadorCaracteres(this.value, this.id)</value>
      <webElementGuid>d444433d-6a85-45af-8a53-90c05454d044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enfermedades&quot;)</value>
      <webElementGuid>646aabb6-4a40-4efb-b082-7edec6af3fd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='enfermedades']</value>
      <webElementGuid>42cc33d4-b280-4534-bb2d-0022f9023616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form']/tbody/tr[4]/td/fieldset/div/table[2]/tbody/tr[12]/td[2]/textarea</value>
      <webElementGuid>1c8d793c-8e34-4d33-9796-2167304ed94c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[26]/following::textarea[1]</value>
      <webElementGuid>1cc08ca8-01a4-44b7-b39d-a80d54f2509b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::textarea[1]</value>
      <webElementGuid>867bd455-b5d6-4565-b0d5-39101f9b8f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alérgico a'])[1]/preceding::textarea[1]</value>
      <webElementGuid>a20ffc1a-06d9-4b6a-aa46-5c5879ed36e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[27]/preceding::textarea[1]</value>
      <webElementGuid>335e1da0-d923-4eb3-a9e1-64dc83d16810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3cc9486a-c3ce-491c-9852-2e2c9f2cbd9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Especifica enfermedad y tratamiento' and @id = 'enfermedades']</value>
      <webElementGuid>b3ec48b6-9040-4bf7-9832-9bfe9d11b762</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
