<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputFechaNacimientoApo</name>
   <tag></tag>
   <elementGuidId>2cce4c36-edfd-41c8-a668-e95577d9ac2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_nac</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apo_nac']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#apo_nac</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2b9a837-5691-424e-b7ae-3bae0c0d432c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>72e508f9-1d6a-4478-9f61-691cee798804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_nac</value>
      <webElementGuid>153d0686-f599-4571-8deb-8b8ad8a0b0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9a84c9c7-f54d-4b79-a581-3a82dc9ddec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_nac</value>
      <webElementGuid>645ba0e8-9ad5-4925-8d68-7f8b2079ef0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_nac&quot;)</value>
      <webElementGuid>4c830173-1c83-4a23-97c0-0d553ca138ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apo_nac']</value>
      <webElementGuid>4a605471-712d-4758-b686-e1249ba82d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>9c372aa9-e777-4260-883e-2380c74a4ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>3dea0ba7-bf1d-46a0-abc3-cb9caf2185e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'apo_nac' and @name = 'apo_nac']</value>
      <webElementGuid>0feb55b8-2e3a-4e3f-9327-622435063f0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
