<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputNPersonasFamilia</name>
   <tag></tag>
   <elementGuidId>8f1a0ca6-6214-4c60-88ee-3dce7dd555d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#n_pgf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='n_pgf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#n_pgf</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>481ccbeb-7469-4645-a570-7d24df2bf0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>37</value>
      <webElementGuid>3a0aba35-db29-4879-8807-63f6ae3a9128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>88659186-447e-4e10-ae35-a3e3b4c3cdc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>586fb1cb-3669-44a2-983a-5a8e17ec4995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>n_pgf</value>
      <webElementGuid>39420ca1-7c4f-40a9-8bd0-de598fadc301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if ((event.keyCode &amp; lt; 48) || (event.keyCode &amp; gt; 57)) event.returnValue = false;</value>
      <webElementGuid>d2660b90-566e-44d4-b66d-09a73c222bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b9b0e2bd-452a-4cf7-87f7-919b4060ba1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n_pgf&quot;)</value>
      <webElementGuid>7c2cc1af-7977-4421-a97f-8af58dfb6fdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='n_pgf']</value>
      <webElementGuid>c72d8b84-5d1d-44db-811f-fa23e8c63f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='new_tabla_apoderados']/fieldset/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>b2150904-0436-4288-bc50-0707fa445c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/fieldset/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>dbd2a8b8-b31b-4717-afcc-54c53df46cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'n_pgf']</value>
      <webElementGuid>ee4106dc-9c1b-4638-a46d-82b5bb1f30cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
