<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_checkRepitePreKin</name>
   <tag></tag>
   <elementGuidId>34e9864f-b0e9-4721-9d77-449fd67a1874</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chk_cr_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chk_cr_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#chk_cr_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb42c7f2-7794-486f-b5d0-52c1d5e44dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4f0b2962-0381-47c7-9eb4-386c06cf75c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chk_cr_1</value>
      <webElementGuid>e9a7882c-33b9-4267-a8e9-ab32080232d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chk_cr_1&quot;)</value>
      <webElementGuid>2b2363a2-68ab-4198-994b-8e25b2045b5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chk_cr_1']</value>
      <webElementGuid>3ff324ce-81ae-4a2a-8152-188812c64ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='repittegrd']/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>ac8e44a0-2fe5-41c8-aecb-5aea2ba52ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>ec37b8e8-d445-40dd-b69b-04397572220f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'chk_cr_1']</value>
      <webElementGuid>aa4581d7-5b07-4a3e-b2c1-ab73183a54df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
