<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputSisSaludApo</name>
   <tag></tag>
   <elementGuidId>66dfbf1a-06bb-4b46-86f8-3588bc9fdcf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_sal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apo_sal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;FONASA/ISAPRE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9da5197-5dfc-4e23-9f46-cc4f08ae487e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a31f668-121a-405a-850e-8c4a8fb59254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0d2ee61f-6f7f-4db7-bff8-e1954cdaae69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_sal</value>
      <webElementGuid>5b7e5005-fb22-4523-a2d6-ead30aa04fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_sal</value>
      <webElementGuid>0770afa9-4a80-4f95-9fef-9cbc80f0e45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>FONASA/ISAPRE</value>
      <webElementGuid>af087cc4-6988-44a8-82ed-aa86090a24b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_sal&quot;)</value>
      <webElementGuid>67fde920-62fa-4c6a-b95f-6f5dadcb7428</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apo_sal']</value>
      <webElementGuid>e8406f91-17fc-4a26-9316-3850a9deced1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[11]/td[2]/input</value>
      <webElementGuid>f8ecb00f-28de-42bf-8168-b44167d209ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[11]/td[2]/input</value>
      <webElementGuid>1ecad002-2675-46cc-a401-ace01f3621fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'apo_sal' and @name = 'apo_sal' and @placeholder = 'FONASA/ISAPRE']</value>
      <webElementGuid>8ef6ecae-8cdc-4e05-86b1-8c98a5a7592b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
