<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_checkRepite5Basico</name>
   <tag></tag>
   <elementGuidId>d7523dcd-7a93-45de-8588-dc53a7a25857</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chk_cr_7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chk_cr_7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#chk_cr_7</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00577995-574d-462a-883a-d475676fbac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8572792b-ee13-43c4-8200-43e2ada8c2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chk_cr_7</value>
      <webElementGuid>f007f249-37bb-4a87-a61a-9d4cf7f55957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chk_cr_7&quot;)</value>
      <webElementGuid>eb233249-4333-471b-99f2-1c801d089848</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chk_cr_7']</value>
      <webElementGuid>6f72efe3-fd9e-4b79-846e-cc0715bf467e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='repittegrd']/td[3]/table/tbody/tr/td[7]/input</value>
      <webElementGuid>71aee343-f58f-403d-9141-7e588d7bbc3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/input</value>
      <webElementGuid>73cc8b2c-76df-4201-bcd3-eb049b5b069e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'chk_cr_7']</value>
      <webElementGuid>1ca3b923-3f9f-4f4d-91e2-27cb78d2e837</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
