<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_checkAlta</name>
   <tag></tag>
   <elementGuidId>97b196c8-d66f-4d8c-986e-92ba5da0d1f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='alta']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#alta</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5afc4c2d-eb01-4c2d-8808-1ae9d75446d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5defc37e-2cbd-48eb-8b76-2b000d4d8c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alta</value>
      <webElementGuid>76d8fe28-4a85-4d1f-9651-7e0f02e0a3b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alta</value>
      <webElementGuid>f4ee2fe1-dc08-449f-b4d5-b3ed53220ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alta&quot;)</value>
      <webElementGuid>b601991d-3ca2-484a-b4f4-d8f2ece17f8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='alta']</value>
      <webElementGuid>224bf5a6-83ab-427c-aa9d-5af76584bec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form_3']/tbody/tr[9]/td[2]/input</value>
      <webElementGuid>bd0771f1-6e7e-45ab-befe-73d2d967ecc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr[9]/td[2]/input</value>
      <webElementGuid>9b530414-55f1-4c9e-9f40-768f76dceea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'alta' and @id = 'alta']</value>
      <webElementGuid>eb78206e-66ec-406f-b1fe-a407976470a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
