<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_radioDuracionPIE_transitorio</name>
   <tag></tag>
   <elementGuidId>2e7500f3-4230-4750-9e63-fb5d20d8bdf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rbtDuracionPie_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rbtDuracionPie_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#rbtDuracionPie_2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ef7f577-6bac-43ee-ba50-e246d341378f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>379a3c9a-459c-42d9-9cdc-806503eb90cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rbtDuracionPie</value>
      <webElementGuid>229990c6-7ff2-45d7-b0ef-6eb9a0032f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rbtDuracionPie_2</value>
      <webElementGuid>354cf1f8-8907-4fc2-95b8-e69fca89e0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>97184783-17ff-41b3-8e01-89283ab1f1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>b230873b-cd82-4437-bbd6-2db3c6237798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rbtDuracionPie_2&quot;)</value>
      <webElementGuid>6a00ec31-d912-43fc-8fa4-7346494541e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rbtDuracionPie_2']</value>
      <webElementGuid>daf3e3b2-b06a-45a8-a7c6-b7304b2d8238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_duracionPie']/td[2]/span[2]/input[2]</value>
      <webElementGuid>c867abe9-6b25-4c9b-84cd-efbcd9478a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[7]/td[2]/span[2]/input[2]</value>
      <webElementGuid>5cfab540-1b32-42c8-a4f0-e328d78902ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'rbtDuracionPie' and @id = 'rbtDuracionPie_2']</value>
      <webElementGuid>8fdeea84-53f7-4c20-9040-b48552421d8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
