<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_radioDuracionPIE_permanente</name>
   <tag></tag>
   <elementGuidId>159ab233-a925-4330-980d-de761ef75cb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rbtDuracionPie_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rbtDuracionPie_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#rbtDuracionPie_3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>862cf1ec-f26b-45dc-a702-f0b78f769da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e08f9403-72a7-4702-9d5e-a559f3435807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rbtDuracionPie</value>
      <webElementGuid>1adeb1e6-4159-4058-9828-6d2603daf226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rbtDuracionPie_3</value>
      <webElementGuid>bea4dab9-8445-4c7a-97e2-965c8c0a0bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>c0702255-be19-4ab0-bd6a-5fcddd0aa25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>7f9c3eb8-455a-4b93-957b-a647730796c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rbtDuracionPie_3&quot;)</value>
      <webElementGuid>2180d70a-c595-4d48-90ac-b94e03f1b855</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rbtDuracionPie_3']</value>
      <webElementGuid>0da7ec24-6c50-42f2-81c6-d690301e25dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_duracionPie']/td[2]/span[2]/input[3]</value>
      <webElementGuid>d6b7c1ce-81a3-41d5-abad-122babd85a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input[3]</value>
      <webElementGuid>18158a54-1344-4a9e-bb3d-c0aeb5edbd44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'rbtDuracionPie' and @id = 'rbtDuracionPie_3']</value>
      <webElementGuid>5bf2a027-6437-44f6-9988-ff1734412bea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
