<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_selectTipoCorreo                                                                                Trabajo                                                                                                 Orga</name>
   <tag></tag>
   <elementGuidId>4fe664dc-9345-40d0-97ce-34423d906062</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tipoCorreo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipoCorreo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tipoCorreo</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>80b9f047-20ce-411a-af4d-33a025a80f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tipoCorreo</value>
      <webElementGuid>08112c28-740d-4001-81a8-d9d2e2244d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipoCorreo</value>
      <webElementGuid>d6cd059b-c0b9-4c62-9fa6-905c06519193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                             Personal
                                                                                                 Trabajo
                                                                                                 Organizacional
                                                                                                 Otro
                                                                                        </value>
      <webElementGuid>0bb50094-919b-4a80-80c4-bcf089d1d0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipoCorreo&quot;)</value>
      <webElementGuid>69db87df-d933-4948-821e-b956d97d328c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipoCorreo']</value>
      <webElementGuid>403876e0-4ad7-4362-8c8b-d33e77e2d794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form']/tbody/tr[4]/td/fieldset/div/table[2]/tbody/tr[8]/td[2]/select</value>
      <webElementGuid>3c70f057-36d0-47b8-ba07-4460d415d0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[19]/following::select[1]</value>
      <webElementGuid>5ef128f7-6e4a-485e-8540-6dc4189dbaca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Correo'])[1]/following::select[1]</value>
      <webElementGuid>21370931-e38b-4635-95b8-df1479d69c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail'])[1]/preceding::select[1]</value>
      <webElementGuid>d4176b38-7b28-46cd-b95f-aff6d29aaf45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[20]/preceding::select[1]</value>
      <webElementGuid>b6c029e1-c97f-4f2b-ada4-963f7b1c216e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[8]/td[2]/select</value>
      <webElementGuid>77095272-55db-42eb-ab1b-6da0237da7c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tipoCorreo' and @id = 'tipoCorreo' and (text() = '
                                                                                             Personal
                                                                                                 Trabajo
                                                                                                 Organizacional
                                                                                                 Otro
                                                                                        ' or . = '
                                                                                             Personal
                                                                                                 Trabajo
                                                                                                 Organizacional
                                                                                                 Otro
                                                                                        ')]</value>
      <webElementGuid>3dce7e1d-2b1c-4df8-bbb4-9dd84711ff2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
