<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputTelefonoApo</name>
   <tag></tag>
   <elementGuidId>433a27d4-3b1b-4e18-b7c2-c3197884e4b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_fono</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apo_fono']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Teléfono: +56&quot;i] >> internal:attr=[placeholder=&quot;98765432&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c581b3fa-1c3c-44b2-8d28-9678b509132d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a8f8bc4f-0554-4fc8-9e07-0fb492d4a514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_fono</value>
      <webElementGuid>df62c6e8-a09f-4c13-88e1-b7513d61c166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_fono</value>
      <webElementGuid>e44c4231-1dcd-4936-8223-8460b5486a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>98765432</value>
      <webElementGuid>18ad9b7e-a5ed-4f5d-a5f6-a770d61576ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if ((event.keyCode &lt; 48) || (event.keyCode > 57)) event.returnValue = false;</value>
      <webElementGuid>dcbe6172-4981-4105-b55f-b8ff9c086e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>64c7db45-e1a3-4709-bb6b-fd0906cfa656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>40f724d4-f106-4b08-bdf7-d70d1fa35e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validarNumeros(this,4);</value>
      <webElementGuid>8528bc85-ff6d-455c-a622-ed8d5d833111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_fono&quot;)</value>
      <webElementGuid>d05db4ed-1643-4675-ba6d-27948d70270e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apo_fono']</value>
      <webElementGuid>497dfc0c-f358-4135-b478-4ca0c8707316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[8]/td[3]/div/div[2]/input</value>
      <webElementGuid>817ec662-5655-4d0d-83dd-e24d31f26ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div[2]/input</value>
      <webElementGuid>c02f0835-7b6b-491d-9049-bdce88d65b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'apo_fono' and @name = 'apo_fono' and @placeholder = '98765432']</value>
      <webElementGuid>febb61c5-59dc-4015-8ded-452fe1239d5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
