<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_selectTipoContacto</name>
   <tag></tag>
   <elementGuidId>f1a432a8-549b-4532-9133-c7bd926082ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tipo_contacto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipo_contacto']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tipo_contacto</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>39fd3c30-a24e-4c9c-953a-5171bd506dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipo_contacto</value>
      <webElementGuid>779c4fc2-b1df-4940-a0ef-644de818b9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desplegable</value>
      <webElementGuid>2a3682d5-bb31-4385-a28c-432671d3680e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                            Tipo contacto
                                                                                                                            Teléfono
                                                                                                                                Celular
                                                                                                                                Correo
                                                                                                                        </value>
      <webElementGuid>d799b11d-0a6e-4385-8b19-7cd4f0015edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipo_contacto&quot;)</value>
      <webElementGuid>bbf25788-d6e7-41c9-a144-a9a1fc2f0466</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipo_contacto']</value>
      <webElementGuid>73d14d3a-2c71-49f1-902d-44398b24ed96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_contactosNew']/table/tbody/tr/td/select</value>
      <webElementGuid>2bad57e6-3547-4143-98b1-c4f6c3058f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[22]/following::select[1]</value>
      <webElementGuid>efe249b4-3584-46de-baca-e1e3fb3e1515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione una opción'])[1]/preceding::select[1]</value>
      <webElementGuid>607943a7-78dc-42a5-b8ff-73806e9b86b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[23]/preceding::select[1]</value>
      <webElementGuid>2c441df0-b785-4c34-b53c-b6a62e95623e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/table/tbody/tr/td/select</value>
      <webElementGuid>edc7f38a-d496-44fc-b029-aea799c23b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'tipo_contacto' and (text() = '
                                                            Tipo contacto
                                                                                                                            Teléfono
                                                                                                                                Celular
                                                                                                                                Correo
                                                                                                                        ' or . = '
                                                            Tipo contacto
                                                                                                                            Teléfono
                                                                                                                                Celular
                                                                                                                                Correo
                                                                                                                        ')]</value>
      <webElementGuid>9b0f594b-e944-45e6-bd81-2f1fc81b5963</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
