<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_radioDuracionPIE_NoEspe</name>
   <tag></tag>
   <elementGuidId>7e1eef1f-60ee-48d7-8a03-b70d6bb698ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rbtDuracionPie_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rbtDuracionPie_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#rbtDuracionPie_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17d7e901-9c4e-4309-89c6-2471b32c333c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>60a8d86f-6f14-44bd-bbfb-204a9a95b204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rbtDuracionPie</value>
      <webElementGuid>cccca4a7-8ccd-4282-8967-fd855ccae6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rbtDuracionPie_1</value>
      <webElementGuid>bfaa153c-d974-443d-9089-832aa31b954d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bddfd157-74fd-47bd-b3f6-7b84a58afe77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>cfc2f204-9c4a-4b69-9729-547cc8e47fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rbtDuracionPie_1&quot;)</value>
      <webElementGuid>214f0548-40d8-4ae9-862c-2f163125ee85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rbtDuracionPie_1']</value>
      <webElementGuid>5b5c7b0f-8823-4fcc-bb5a-de34707437dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_duracionPie']/td[2]/span[2]/input</value>
      <webElementGuid>9f9e7606-f824-4fd2-89e0-3954430ff3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[7]/td[2]/span[2]/input</value>
      <webElementGuid>b6e654d8-21d3-403d-bea0-ce043486b5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'rbtDuracionPie' and @id = 'rbtDuracionPie_1']</value>
      <webElementGuid>372ecfa7-8d0f-4793-8af9-bd855fbe3292</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
