<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputOcupacionApo</name>
   <tag></tag>
   <elementGuidId>8f6329d5-84d5-4bc6-87e5-8a19beaeae04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_ocu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apo_ocu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Trabajo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d85dd83-6dd3-4a4d-873f-42640e1068ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5587c6dc-5728-45c9-b8b5-debd3b95c153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_ocu</value>
      <webElementGuid>c9b898c5-c945-4622-852a-35ac62c2f00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>18c89590-ea97-464f-af9c-e513c98ac874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_ocu</value>
      <webElementGuid>5c0610cf-6e61-4a58-9c6e-2aad77016719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Trabajo</value>
      <webElementGuid>37cf38bf-810b-4e54-b479-d9c25773a665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_ocu&quot;)</value>
      <webElementGuid>27e4a109-9081-49b0-a176-aa379d8d8779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apo_ocu']</value>
      <webElementGuid>083467a2-f434-47f1-aa25-d9ea9bcb6ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[11]/td/input</value>
      <webElementGuid>08864006-fab7-49b1-83b6-b635690f26aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[11]/td/input</value>
      <webElementGuid>291c2041-7a28-4ee2-9fd8-ba05dc89c57e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'apo_ocu' and @name = 'apo_ocu' and @placeholder = 'Trabajo']</value>
      <webElementGuid>c644a003-3d5a-4682-b859-6e97accd1aa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
