<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_checkApoTitular</name>
   <tag></tag>
   <elementGuidId>eb4e2064-7035-4819-8fa4-107dadbbd60e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_pri</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apo_pri']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#apo_pri</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5063ef4e-8498-4de5-a091-dcc3fcbeab01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7da68f7e-2009-4293-88b6-e98528bb5af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_pri</value>
      <webElementGuid>e0a15d8c-6dff-4f3e-b46f-4d83448b21a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_pri</value>
      <webElementGuid>c097dd91-67ad-4b58-8d72-6c943f1c2d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_pri&quot;)</value>
      <webElementGuid>5e805c55-7eb6-4ddb-a901-6107c7e636c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apo_pri']</value>
      <webElementGuid>e11b596d-3998-4f68-9e11-0c781e2d3551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[11]/td[5]/input</value>
      <webElementGuid>04948b22-91f1-49da-a6fd-8ad5c4723e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td[5]/input</value>
      <webElementGuid>e732e384-c40b-4e67-ad8a-21b42138c57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'apo_pri' and @name = 'apo_pri']</value>
      <webElementGuid>c79862fa-6527-4102-90c8-d5ced4f735ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
