<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputCorreoApoderado</name>
   <tag></tag>
   <elementGuidId>96dacccb-a67d-4c71-88d7-475ac36da72a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apo_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;correo@email.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f056f9aa-bc81-4534-8099-c97f80616598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fabbaa25-dca6-45a4-9963-6329bc62a115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4bf8e28f-9c93-4265-bb0f-d32529f1e684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_email</value>
      <webElementGuid>c74b196a-70f2-4b21-9e03-5fcf1f89bf0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_email</value>
      <webElementGuid>aefeb08b-1a74-43d4-beed-3deedfc0e4e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>correo@email.com</value>
      <webElementGuid>69e65649-5aae-440d-b446-dc193ca41771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_email&quot;)</value>
      <webElementGuid>f8ad5412-2da2-4866-81bb-d97617819fd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apo_email']</value>
      <webElementGuid>434c9cca-5cf5-4c01-b8ff-49d6bc03ee1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[8]/td/input</value>
      <webElementGuid>3db9d1d7-16ea-4878-b5e4-2c81a628f6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[8]/td/input</value>
      <webElementGuid>e07a285b-d041-4a20-a234-d5b98bb29598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'apo_email' and @name = 'apo_email' and @placeholder = 'correo@email.com']</value>
      <webElementGuid>ae8ff27e-f8f7-4f95-a5a0-632a4b6db6e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
