<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputFechaIncorporacion</name>
   <tag></tag>
   <elementGuidId>51651ae4-11b9-414d-9170-82ef9cddad2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#incorporacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='incorporacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#incorporacion</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16bf6624-0899-4a5c-b0ff-aa6816968d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce6380e0-ec2a-4c23-a30f-c020c3865179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker hasDatepicker</value>
      <webElementGuid>ee38727a-262e-40e7-89ca-34230b3c9c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>incorporacion</value>
      <webElementGuid>03d50a66-563f-4b4c-9efe-0a95e04c4874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>incorporacion</value>
      <webElementGuid>d2b6c7e0-2c1a-49dc-8eac-c1ae944d9722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>a3b4fabb-5b0f-4c7f-b49a-86ed58503721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;incorporacion&quot;)</value>
      <webElementGuid>e14f0824-7679-4f91-8258-b39a3887657f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='incorporacion']</value>
      <webElementGuid>0eae844a-bf28-4c50-8b7a-7b28eac4b4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form_2']/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>15f9d28f-57fd-45d8-bd9c-ee9a5ff8c85d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>e06e6b1e-6b34-410f-b20d-7704e6877241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'incorporacion' and @id = 'incorporacion']</value>
      <webElementGuid>783952c4-ef1c-4c09-ad34-02e08a73cbdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
