<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_checkCargaSaludApo</name>
   <tag></tag>
   <elementGuidId>f8024c85-6f5f-4df8-a156-13fc2b8c07b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apo_car</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apo_car']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#apo_car</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f61c2a21-ecbd-4f5d-808e-bf95324115e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>374e27d2-f96a-4f67-b6bb-d8d10c7aed29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apo_car</value>
      <webElementGuid>3fe456b5-6ae8-4404-a04c-d302f79a3379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apo_car</value>
      <webElementGuid>e5306268-f32c-4164-b005-96165ba82d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apo_car&quot;)</value>
      <webElementGuid>621b4528-535d-4ed3-8f4c-fd26bc5c5089</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apo_car']</value>
      <webElementGuid>eef88701-3659-451f-a854-5225eb9d28dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_apoderados']/div/div/form/table/tbody/tr[11]/td[3]/input</value>
      <webElementGuid>7b6520e8-f76d-402d-a599-4a1bfd14716f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td[3]/input</value>
      <webElementGuid>8b841d53-ca61-43d2-ba19-ca55ceee3c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'apo_car' and @name = 'apo_car']</value>
      <webElementGuid>c5131bcf-103f-448f-b51b-dceaef60bdaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
