<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputContactoNuevo</name>
   <tag></tag>
   <elementGuidId>54eb07bd-c6b5-4984-b566-7eaabca19d69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nuevo_contacto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nuevo_contacto']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Agregar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60482e00-061c-4e63-9c83-b1adc00bbecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nuevo_contacto</value>
      <webElementGuid>1e2dac22-488c-4abd-b974-37871cdb341e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04fb9b2c-c70d-489f-9d7c-560119cf8200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desplegable</value>
      <webElementGuid>05638fd9-b6c2-4d17-9080-e4de6d0e9ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Agregar</value>
      <webElementGuid>16e439f7-4aca-4325-a83a-a5a385ef5476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nuevo_contacto&quot;)</value>
      <webElementGuid>ec43fc51-b9c2-4f0e-9229-2dc73565b35d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nuevo_contacto']</value>
      <webElementGuid>2cbfab22-b592-4cc5-abfc-8bd8fe96ec42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_contactosNew']/table/tbody/tr[2]/td/input</value>
      <webElementGuid>c7085f4a-6047-4624-8564-f7851a1db321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>ad90c4af-f5e8-4534-be6e-2c30666600a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nuevo_contacto' and @type = 'text' and @placeholder = 'Agregar']</value>
      <webElementGuid>6331654a-9e70-4621-92db-0c03080fdc40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
