<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_check3Colacion</name>
   <tag></tag>
   <elementGuidId>fac3bab5-66eb-4e29-9dea-490152566561</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OtrBen2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OtrBen2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;3era colación&quot;s] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd460404-b139-4305-a24b-f856046cd2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d13fa976-c1eb-42b3-80c0-1afbe55cc555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OtrBen2</value>
      <webElementGuid>80b45e82-0c78-4f4b-b558-12c07cac74e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OtrBen2&quot;)</value>
      <webElementGuid>91a57362-7392-4f09-ad5b-ec36bb55db58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OtrBen2']</value>
      <webElementGuid>a3e17784-5ab0-4dc3-a9fc-c43009f0e519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='otros_beneficios']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>4a17892b-6e67-47d5-9e19-6526b6e1f326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>55166cc4-fdfc-4f8a-90f1-22ab9e007301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'OtrBen2']</value>
      <webElementGuid>0552a3d1-8635-4f7a-b22e-1b85c9ed3867</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
