<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_buttonQuitarPie</name>
   <tag></tag>
   <elementGuidId>cb4e2708-ed78-49b4-a25d-68722647c1f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnRemove_302</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DynamicPie']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;-&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>86bfd322-0be9-4327-8abc-235d84a5c693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnRemove_302</value>
      <webElementGuid>7d21db31-5e49-4237-ac7d-779fabdd8322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-purple waves-effect waves-light</value>
      <webElementGuid>0b513e95-7649-423a-be95-d309e7d6b0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>quitarPieAdicional2(idPieAdicional_302,btnRemove_302)</value>
      <webElementGuid>dce57f19-1f3b-4199-9f90-b6bcc1637e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>f5cc2da8-2ce8-4642-b24d-a6a0fba06b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnRemove_302&quot;)</value>
      <webElementGuid>d4e76caa-c68c-4b9d-be77-355868b08f1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnRemove_302']</value>
      <webElementGuid>2045b8d5-36a8-435b-9850-cadf52e97a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DynamicPie']/button</value>
      <webElementGuid>6392a096-049c-4bbc-92a8-bdfd4a9671d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[35]/following::button[1]</value>
      <webElementGuid>8802cd77-27d0-42e8-8ec2-ce1ff0a5be1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duración Pie'])[1]/preceding::button[1]</value>
      <webElementGuid>0577ee88-aac4-4a37-aa0e-60bb1dd46a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[36]/preceding::button[1]</value>
      <webElementGuid>c0719f67-9647-435d-b653-36147880fb1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='-']/parent::*</value>
      <webElementGuid>c378fd77-10c3-47a4-b9fe-92173bb07e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/button</value>
      <webElementGuid>cd56b032-c5b4-4658-a775-3003abd7f6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnRemove_302' and (text() = '-' or . = '-')]</value>
      <webElementGuid>a39b15b7-6337-4580-a2f4-8bfac37ec162</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
