<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputBecaOtra</name>
   <tag></tag>
   <elementGuidId>25e2525d-0ea8-429f-afd5-c96c8793ed7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#becaExtra</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='becaExtra']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#becaExtra</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73f49a04-6acb-41fb-857e-432886abf16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c36d9da4-1ba2-415e-a5a9-bc29b19634c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>becaExtra</value>
      <webElementGuid>90513393-6329-4cba-8477-0982bd99e23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>1fcb874f-1dd3-4990-81bf-a75d4bbafb41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;becaExtra&quot;)</value>
      <webElementGuid>af3629e1-aa78-49a9-ba1a-043150b6964a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='becaExtra']</value>
      <webElementGuid>8a89d851-ee9b-4395-a087-066309137fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='priotrabeca']/td[3]/table/tbody/tr/td[6]/input</value>
      <webElementGuid>4127ebc9-821a-4359-8b8e-1efed24dac5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>95d6e915-4238-4823-928d-4022017d33eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'becaExtra']</value>
      <webElementGuid>68fde8c7-870a-4a15-8c99-50ab3d03cf22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
