<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_selectComuna</name>
   <tag></tag>
   <elementGuidId>0b21435f-7fa5-483e-a5c6-89135c65ef3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comuna</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='comuna']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#comuna</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4286cae0-c403-4b37-9519-c7c3358a5455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comuna</value>
      <webElementGuid>02fcf445-e858-451b-865c-b34026ccdd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comuna</value>
      <webElementGuid>d5f744c2-95b1-4e6b-b683-cb8fbbc9cc3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>8bf310a0-f045-4c69-b784-10ebc81c41a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>            Sin Datos            
            </value>
      <webElementGuid>f2138067-794a-432d-872b-60009624a03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comuna&quot;)</value>
      <webElementGuid>61603370-4773-437c-8e36-cb07e0ac6777</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='comuna']</value>
      <webElementGuid>f6529738-8d24-4786-96dc-9c3157fb5cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form']/tbody/tr[4]/td/fieldset/div/table[2]/tbody/tr[3]/td[2]/select</value>
      <webElementGuid>06dbda7e-8215-4bd3-a985-0620948a6a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[14]/following::select[1]</value>
      <webElementGuid>8e54a0e3-65c2-4e21-8156-0a32ddc729df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comuna'])[1]/following::select[1]</value>
      <webElementGuid>0686a5a6-f055-414a-8c86-576f7b329feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Codigo Postal'])[1]/preceding::select[1]</value>
      <webElementGuid>ea4b4eb8-38a9-4542-ac27-dfd0abf8befe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[15]/preceding::select[1]</value>
      <webElementGuid>934d6250-40b5-4975-b11b-2b5407ca5d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/select</value>
      <webElementGuid>b29b48e3-052d-4c8b-b88c-a92e0fb1a6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'comuna' and @id = 'comuna' and (text() = '            Sin Datos            
            ' or . = '            Sin Datos            
            ')]</value>
      <webElementGuid>cc1ea3d0-9e37-4563-acc8-61f8e3104313</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
