<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_radioButtonFemenino</name>
   <tag></tag>
   <elementGuidId>30a435d1-12c8-405e-b951-00ca0c33b8ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='genero'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#genero >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17a4d990-1e73-4628-97f8-62ca6d7ed48a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>05ad34c0-5dcf-4c1e-a043-8db56bd3a98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>genero</value>
      <webElementGuid>a741a042-5127-49aa-949a-e2b9b66ff032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>genero</value>
      <webElementGuid>0f43c682-0ac2-46a7-916a-83a7bc27cc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2a42ce1f-12a1-4013-9a66-a0f6cd79da18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>4d015fb8-9f0f-4a73-a914-8b1c515f9f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_form&quot;)/tbody[1]/tr[4]/td[1]/fieldset[@class=&quot;fieldset-matricula&quot;]/div[@class=&quot;tablas-matricula&quot;]/table[@class=&quot;tbl-matricula-1&quot;]/tbody[1]/tr[7]/td[@class=&quot;input-genero&quot;]/span[2]/input[@id=&quot;genero&quot;]</value>
      <webElementGuid>a22a43a0-0bf1-4159-9b5a-89daa5cc4ef5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='genero'])[2]</value>
      <webElementGuid>110de959-fcd2-462c-8809-46fe596cf7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form']/tbody/tr[4]/td/fieldset/div/table/tbody/tr[7]/td[2]/span[2]/input[2]</value>
      <webElementGuid>1db62015-b5c5-4b6f-9ed6-073d390b7c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/span[2]/input[2]</value>
      <webElementGuid>5db79d43-05dc-4ce6-875a-5d67f9f80304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'genero' and @id = 'genero']</value>
      <webElementGuid>96101915-9155-4648-8da1-9deab534869f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
