<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputColegioProcedencia</name>
   <tag></tag>
   <elementGuidId>ae7fb38f-4c8f-42e1-9e35-f8805312c978</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#procedencia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='procedencia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#procedencia</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b32dad1c-e351-444f-8c18-2c5a9813ad0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a29d0d4f-475f-41bb-a2b1-8fc8ad91ae38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>procedencia</value>
      <webElementGuid>9e299bbc-e98e-4a55-892c-435a8d039d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desplegable</value>
      <webElementGuid>5797e6a0-9511-4686-b970-252a4e62c862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>procedencia</value>
      <webElementGuid>d2632a23-7f7f-49ec-ac5f-2a5872ed43a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>60b8de87-f56d-4943-a307-c8e5f2aee747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;procedencia&quot;)</value>
      <webElementGuid>22f407c4-2029-4ab7-b341-a82b7e463b35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='procedencia']</value>
      <webElementGuid>6abfefa7-7815-491e-b809-eaa1122c7ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form_3']/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>7e8e61d9-1a9c-40f0-ad86-aec4ef322047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>7e21c968-8c13-4d56-8424-934059ec103e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'procedencia' and @id = 'procedencia']</value>
      <webElementGuid>5c09451c-7c80-4082-a9c0-7f24be72d2f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
