<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_checkPIE</name>
   <tag></tag>
   <elementGuidId>e5ea93f4-f035-4605-a00e-1e472cd2574a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#esPie</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table_form_2']/tbody/tr[5]/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#esPie</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2ee4a52-b194-4ac1-b431-4de488f297ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9b187f36-1b92-430e-a3f0-187fb752a918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>esPie</value>
      <webElementGuid>a3b185a6-8e49-4259-aeb5-bfde3654a46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>esPie</value>
      <webElementGuid>6cb06420-a957-4696-b77a-44c9f3267e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>seleccion(2);</value>
      <webElementGuid>cfcb0a97-3c25-4851-8d69-869b2eba232f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>ab3616ea-4eb2-49c7-ad02-771b24ae8470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;esPie&quot;)</value>
      <webElementGuid>dfee9416-516f-4900-bd3e-3411871679d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='esPie']</value>
      <webElementGuid>25cfb32e-8488-42f6-ae4d-b1f6c070f4f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form_2']/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>6c73f503-22ec-4117-8b7b-0f5febbd4887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>ef080f55-33fe-4941-9513-ac7c8db05a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'esPie' and @id = 'esPie']</value>
      <webElementGuid>7f3fc3dc-cf2c-423f-9145-ebe34d9fbd6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
