<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputTeleCasa</name>
   <tag></tag>
   <elementGuidId>dfe16488-3aab-4593-9590-f13c05a5bd79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#telefono</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='telefono']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#telefono</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a48e1fa8-e934-4d7f-8e3a-a53339567c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0c6f1c51-6a4f-4252-8db1-6644275fa9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>e79a6f08-0e89-4004-acc8-d6ba9b6ecce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desplegable</value>
      <webElementGuid>7ea0c3f7-e140-4f2d-9d5a-2b83faf0ddbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>telefono</value>
      <webElementGuid>1576912e-f36d-46a2-b7ae-d4ed5cc228e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>telefono</value>
      <webElementGuid>3d01a361-6843-43eb-a859-2bf49882c029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>5a261754-75a0-45eb-879d-fdba63d6fe3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if ((event.keyCode &lt; 48) || (event.keyCode > 57)) event.returnValue = false;</value>
      <webElementGuid>948d2a7c-5e91-488d-98cd-928607b2bab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validarNumeros(this,2);</value>
      <webElementGuid>d695583f-149b-4262-8d3a-a3f017e6fb06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;telefono&quot;)</value>
      <webElementGuid>1021af0f-703f-488f-a04f-b7cba34236d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='telefono']</value>
      <webElementGuid>0d3ae6ec-118c-4303-9494-51e87957e080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form']/tbody/tr[4]/td/fieldset/div/table[2]/tbody/tr[7]/td[2]/div/div/div[2]/input</value>
      <webElementGuid>ce2bc431-1815-49d4-874c-f69a45afb4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/div/div/div[2]/input</value>
      <webElementGuid>e688d000-0f87-4165-87af-028f4170b072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'telefono' and @id = 'telefono']</value>
      <webElementGuid>fbb63748-9424-466f-9eea-bb8af346f9c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
